### PR TITLE
Feature/ugo/signup

### PR DESCRIPTION
**Pull request by EngrEric**

### CODE REVIEW

**Comment by Okoli-Ryan** [comment]
Signup page

**Review by EngrEric — COMMENTED** [review]
@Okoli-Ryan  very good work, few things.
1. this branch has conflict with the master branch
2. the formatting is wrong. You'll need to install prettier extension in your vs code to help you format the code

**Comment by Okoli-Ryan** [comment]
So i should pull first and commit again? I already use prettier

**Comment by EngrEric** [comment]
> So i should pull first and commit again? I already use prettier

1. checkout to master `- git checkout master`
2. pull latest master - `git pull origin master`
3. checkout to this branch - `git checkout feature/ugo/signup`
4. merge master to this branch - `git merge master`
5. Resolve the conflict by accepting the right changes you want. 
6. commit after resolving and push - `git push origin feature/ugo/signup`

**Comment by EngrEric** [comment]
@Okoli-Ryan  do not add the verification to this branch, create a new branch for it

**Comment by Okoli-Ryan** [comment]
I've already merged the verification to it.. Is there a fix or should i leave it like that

**Comment by EngrEric** [comment]
> I've already merged the verification to it.. Is there a fix or should i leave it like that

No problem, finish it up, next time. Each feature or bug fix should be in a separate branch

**Comment by Okoli-Ryan** [comment]
I've pushed the changes to the feature/ugo/signup branch. So I don't need to make another pull request, because I can't see my commits on this page

**Pull request merged**
